# Generated by Django 6.0.5 on 2026-05-19 00:30

import apps.condutores.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.CharField(blank=True, help_text='Gerado automaticamente (ex: COND-00042)', max_length=20, unique=True, verbose_name='Prontuário')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.condutores.models._foto_upload, verbose_name='Foto')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$', 'CPF inválido')], verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('orgao_emissor', models.CharField(max_length=30, verbose_name='Órgão emissor')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('unidade', models.CharField(blank=True, max_length=100, verbose_name='Unidade')),
                ('cnh_categoria', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE'), ('ACC', 'ACC')], max_length=3, verbose_name='Categoria CNH')),
                ('cnh_numero', models.CharField(blank=True, max_length=11, verbose_name='Número CNH')),
                ('cnh_emissao', models.DateField(blank=True, null=True, verbose_name='Emissão CNH')),
                ('cnh_vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento CNH')),
                ('cnh_orgao', models.CharField(blank=True, max_length=30, verbose_name='Órgão expedidor CNH')),
                ('cnh_arquivo', models.FileField(blank=True, null=True, upload_to=apps.condutores.models._cnh_upload, verbose_name='CNH digitalizada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condutores', to='usuarios.secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Condutor',
                'verbose_name_plural': 'Condutores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Acidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('veiculo_placa', models.CharField(blank=True, max_length=10, verbose_name='Placa do veículo')),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acidentes', to='condutores.condutor')),
            ],
            options={
                'verbose_name': 'Acidente',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(max_length=120, verbose_name='Tipo de infração')),
                ('pontos', models.PositiveSmallIntegerField(default=0, verbose_name='Pontos')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor (R$)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infracoes', to='condutores.condutor')),
            ],
            options={
                'verbose_name': 'Infração',
                'verbose_name_plural': 'Infrações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição')),
                ('data', models.DateField(verbose_name='Data de conclusão')),
                ('carga_horaria', models.PositiveSmallIntegerField(default=0, verbose_name='Carga horária (h)')),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacoes', to='condutores.condutor')),
            ],
            options={
                'verbose_name': 'Qualificação',
                'verbose_name_plural': 'Qualificações',
                'ordering': ['-data'],
            },
        ),
    ]
