# Generated by Django 6.0.5 on 2026-05-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condutores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condutor',
            name='prontuario',
            field=models.CharField(help_text='Número de prontuário funcional do servidor na prefeitura', max_length=20, unique=True, verbose_name='Prontuário'),
        ),
    ]
