# Generated by Django 6.0.5 on 2026-05-19 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condutores', '0002_prontuario_obrigatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolgaFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERIAS', 'Férias'), ('FOLGA', 'Folga'), ('LICENCA', 'Licença'), ('OUTRO', 'Outro')], default='FERIAS', max_length=10, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Fim')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folgas', to='condutores.condutor')),
            ],
            options={
                'verbose_name': 'Folga / Férias',
                'verbose_name_plural': 'Folgas / Férias',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Penalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADVERTENCIA', 'Advertência'), ('SUSPENSAO', 'Suspensão'), ('DEMISSAO', 'Demissão'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalidades', to='condutores.condutor')),
            ],
            options={
                'verbose_name': 'Penalidade',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
