# Generated by Django 6.0.5 on 2026-05-21 00:03

import apps.veiculos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}[\\-]?\\d{4}$|^[A-Z]{3}\\d[A-Z]\\d{2}$', 'Placa inválida. Use AAA-0000 ou Mercosul AAA0A00.')], verbose_name='Placa')),
                ('marca', models.CharField(max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('renavam', models.CharField(max_length=11, unique=True, verbose_name='RENAVAM')),
                ('prefixo', models.CharField(blank=True, max_length=20, verbose_name='Prefixo')),
                ('num_patrimonio', models.CharField(blank=True, max_length=30, verbose_name='Nº de Patrimônio')),
                ('tipo_veiculo', models.CharField(choices=[('AUTOMOVEL', 'Automóvel'), ('CAMINHAO', 'Caminhão'), ('ONIBUS', 'Ônibus'), ('MOTOCICLETA', 'Motocicleta'), ('MAQUINA', 'Máquina'), ('VAN', 'Van'), ('UTILITARIO', 'Utilitário')], max_length=12, verbose_name='Tipo de Veículo')),
                ('ano_fabricacao', models.PositiveSmallIntegerField(verbose_name='Ano de Fabricação')),
                ('motor_potencia', models.CharField(blank=True, max_length=50, verbose_name='Motor / Potência')),
                ('combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel'), ('FLEX', 'Flex'), ('ELETRICO', 'Elétrico'), ('GNV', 'GNV')], max_length=10, verbose_name='Combustível')),
                ('cap_tanque', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Capacidade do Tanque (L)')),
                ('consumo_ref', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Consumo de Referência (km/L)')),
                ('cap_passageiros', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capacidade de Passageiros')),
                ('cor', models.CharField(blank=True, max_length=40, verbose_name='Cor')),
                ('transmissao', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática'), ('CVT', 'CVT'), ('SEMI_AUTO', 'Semi-automática')], max_length=12, verbose_name='Transmissão')),
                ('pneu_dim', models.CharField(blank=True, max_length=20, verbose_name='Dimensão dos Pneus')),
                ('km_entrada', models.PositiveIntegerField(verbose_name='KM de Entrada')),
                ('ultimo_km', models.PositiveIntegerField(default=0, verbose_name='Último KM')),
                ('estado_conservacao', models.CharField(choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], max_length=10, verbose_name='Estado de Conservação')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=14, verbose_name='Status')),
                ('valor_fipe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor FIPE (R$)')),
                ('tipo_frota', models.CharField(choices=[('PROPRIO', 'Próprio'), ('LOCADO', 'Locado'), ('ESTADUAL', 'Estadual'), ('DOACAO', 'Doação')], max_length=10, verbose_name='Tipo de Frota')),
                ('locadora', models.CharField(blank=True, max_length=100, verbose_name='Locadora / Proprietário')),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Aluguel/mês (R$)')),
                ('dt_ini_contrato', models.DateField(blank=True, null=True, verbose_name='Início do Contrato')),
                ('dt_fim_contrato', models.DateField(blank=True, null=True, verbose_name='Fim do Contrato')),
                ('unidade', models.CharField(blank=True, max_length=100, verbose_name='Unidade')),
                ('centro_custo', models.CharField(max_length=50, verbose_name='Centro de Custo')),
                ('crlv', models.FileField(blank=True, null=True, upload_to=apps.veiculos.models._crlv_upload, verbose_name='CRLV')),
                ('foto_frente', models.ImageField(blank=True, null=True, upload_to=apps.veiculos.models._foto_frente_upload, verbose_name='Foto — Frente')),
                ('foto_lateral_e', models.ImageField(blank=True, null=True, upload_to=apps.veiculos.models._foto_le_upload, verbose_name='Foto — Lat. Esq.')),
                ('foto_lateral_d', models.ImageField(blank=True, null=True, upload_to=apps.veiculos.models._foto_ld_upload, verbose_name='Foto — Lat. Dir.')),
                ('foto_traseira', models.ImageField(blank=True, null=True, upload_to=apps.veiculos.models._foto_tras_upload, verbose_name='Foto — Traseira')),
                ('foto_hodometro', models.ImageField(blank=True, null=True, upload_to=apps.veiculos.models._foto_hod_upload, verbose_name='Foto — Hodômetro')),
                ('outros_docs', models.FileField(blank=True, null=True, upload_to=apps.veiculos.models._docs_upload, verbose_name='Outros Documentos')),
                ('eq_ar_condicionado', models.BooleanField(default=False, verbose_name='Ar-condicionado')),
                ('eq_direcao_hidraulica', models.BooleanField(default=False, verbose_name='Direção hidráulica / elétrica')),
                ('eq_vidros_eletricos', models.BooleanField(default=False, verbose_name='Vidros elétricos')),
                ('eq_som_multimidia', models.BooleanField(default=False, verbose_name='Som / Multimídia')),
                ('eq_radio_comunicador', models.BooleanField(default=False, verbose_name='Rádio comunicador')),
                ('eq_rodas_liga_leve', models.BooleanField(default=False, verbose_name='Rodas de liga leve')),
                ('eq_camera_re', models.BooleanField(default=False, verbose_name='Câmera de ré')),
                ('eq_sensor_estac', models.BooleanField(default=False, verbose_name='Sensor de estacionamento')),
                ('eq_outros', models.TextField(blank=True, verbose_name='Outros equipamentos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='usuarios.secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
    ]
