# Generated by Django 6.0.5 on 2026-05-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_seed_lookup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='unidade',
        ),
    ]
