# Generated by Django 6.0.5 on 2026-05-20 22:42

import apps.multas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condutores', '0003_penalidade_folgaferias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('data_infracao', models.DateField(verbose_name='Data da infração')),
                ('tipo_infracao', models.CharField(choices=[('VELOCIDADE', 'Velocidade'), ('SINALIZACAO', 'Sinalização'), ('ESTACIONAMENTO', 'Estacionamento'), ('ULTRAPASSAGEM', 'Ultrapassagem proibida'), ('SEMAFORO', 'Semáforo'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('codigo_denatran', models.CharField(blank=True, max_length=20, verbose_name='Código DENATRAN')),
                ('pontos', models.PositiveSmallIntegerField(default=0, verbose_name='Pontos na CNH')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CONTESTADA', 'Contestada'), ('VENCIDA', 'Vencida')], default='PENDENTE', max_length=12, verbose_name='Status')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento pagamento')),
                ('prazo_indicacao', models.DateField(blank=True, null=True, verbose_name='Prazo para indicação do condutor')),
                ('prazo_defesa', models.DateField(blank=True, null=True, verbose_name='Prazo para defesa prévia')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=apps.multas.models._multa_upload, verbose_name='Notificação (PDF)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='condutores.condutor', verbose_name='Condutor')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-data_infracao'],
            },
        ),
    ]
