# Generated by Django 6.0.5 on 2026-06-14 22:20

import apps.manutencao.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0004_remove_unidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Número')),
                ('etapa', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('RECEPCAO', 'Recepção'), ('DIAGNOSTICO', 'Diagnóstico'), ('ORCAMENTO', 'Orçamento'), ('APROVACAO', 'Aprovação'), ('EXECUCAO', 'Execução'), ('RETIRADA', 'Retirada'), ('EMISSAO_NF', 'Emissão de NF'), ('FINALIZADO', 'Finalizado')], default='SOLICITACAO', max_length=15, verbose_name='Etapa atual')),
                ('urgencia', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('EMERGENCIA', 'Emergência')], default='MEDIA', max_length=10, verbose_name='Urgência')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do problema / falha')),
                ('num_processo', models.CharField(blank=True, max_length=50, verbose_name='Nº Processo / SEI')),
                ('km_entrada', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na entrada')),
                ('km_saida', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na saída')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico técnico')),
                ('dt_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de solicitação')),
                ('dt_recepcao', models.DateTimeField(blank=True, null=True, verbose_name='Data de recepção')),
                ('dt_diagnostico', models.DateTimeField(blank=True, null=True, verbose_name='Data de diagnóstico')),
                ('dt_inicio_exec', models.DateTimeField(blank=True, null=True, verbose_name='Início da execução')),
                ('dt_retirada', models.DateTimeField(blank=True, null=True, verbose_name='Data de retirada')),
                ('dt_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de finalização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smvs_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smvs', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'SMV',
                'verbose_name_plural': 'SMVs',
                'ordering': ['-numero'],
                'permissions': [('pode_recepcionar', 'Pode recepcionar SMV'), ('pode_diagnosticar', 'Pode registrar diagnóstico'), ('pode_aprovar', 'Pode aprovar orçamento (Fiscal do Contrato)')],
            },
        ),
        migrations.CreateModel(
            name='SMVAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('RECEPCAO', 'Recepção'), ('DIAGNOSTICO', 'Diagnóstico'), ('ORCAMENTO', 'Orçamento'), ('APROVACAO', 'Aprovação'), ('EXECUCAO', 'Execução'), ('RETIRADA', 'Retirada'), ('EMISSAO_NF', 'Emissão de NF'), ('FINALIZADO', 'Finalizado')], max_length=15, verbose_name='Etapa')),
                ('tipo', models.CharField(choices=[('FOTO_ENTRADA', 'Foto de entrada'), ('FOTO_SAIDA', 'Foto de saída'), ('FOTO_PECA', 'Foto de peça substituída'), ('LAUDO', 'Laudo técnico'), ('TESTE', 'Resultado de teste'), ('OUTRO', 'Outro')], default='OUTRO', max_length=12, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=apps.manutencao.models._anexo_upload, verbose_name='Arquivo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('smv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='manutencao.smv')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['etapa', 'enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='SMVChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7, verbose_name='Tipo')),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('ok', models.BooleanField(default=False, verbose_name='OK')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('smv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='manutencao.smv')),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Itens de checklist',
                'ordering': ['tipo', 'item'],
            },
        ),
        migrations.CreateModel(
            name='SMVEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_de', models.CharField(blank=True, choices=[('SOLICITACAO', 'Solicitação'), ('RECEPCAO', 'Recepção'), ('DIAGNOSTICO', 'Diagnóstico'), ('ORCAMENTO', 'Orçamento'), ('APROVACAO', 'Aprovação'), ('EXECUCAO', 'Execução'), ('RETIRADA', 'Retirada'), ('EMISSAO_NF', 'Emissão de NF'), ('FINALIZADO', 'Finalizado')], max_length=15, verbose_name='De')),
                ('etapa_para', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('RECEPCAO', 'Recepção'), ('DIAGNOSTICO', 'Diagnóstico'), ('ORCAMENTO', 'Orçamento'), ('APROVACAO', 'Aprovação'), ('EXECUCAO', 'Execução'), ('RETIRADA', 'Retirada'), ('EMISSAO_NF', 'Emissão de NF'), ('FINALIZADO', 'Finalizado')], max_length=15, verbose_name='Para')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('smv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='manutencao.smv')),
            ],
            options={
                'verbose_name': 'Histórico de etapa',
                'verbose_name_plural': 'Histórico de etapas',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='SMVNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=20, verbose_name='Número da NF')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('cnpj_prestador', models.CharField(max_length=18, verbose_name='CNPJ do prestador')),
                ('razao_social', models.CharField(blank=True, max_length=120, verbose_name='Razão social')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total (R$)')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to=apps.manutencao.models._nf_upload, verbose_name='PDF da NF')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de conferência'), ('EM_CORRECAO', 'Solicitada correção'), ('CONFERIDA', 'Conferida e aprovada')], default='PENDENTE', max_length=12, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('smv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='manutencao.smv')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['smv', 'data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='SMVItemNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PECA', 'Peça'), ('SERVICO', 'Serviço')], max_length=8, verbose_name='Tipo')),
                ('tipo_servico', models.CharField(blank=True, choices=[('MECANICA', 'Mecânica geral'), ('ELETRICA', 'Elétrica'), ('FUNILARIA', 'Funilaria / Pintura'), ('HIDRAULICA', 'Hidráulica'), ('PNEUS', 'Pneus / Borracharia'), ('AR_COND', 'Ar-condicionado'), ('VIDROS', 'Vidros'), ('REVISAO', 'Revisão periódica'), ('OUTRO', 'Outro')], max_length=12, verbose_name='Tipo de serviço')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unidade', models.CharField(default='UN', max_length=10, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Valor total (R$)')),
                ('horas_mo', models.DecimalField(blank=True, decimal_places=2, help_text='Preencher apenas para serviços', max_digits=6, null=True, verbose_name='Horas de MO')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='manutencao.smvnotafiscal')),
            ],
            options={
                'verbose_name': 'Item de NF',
                'verbose_name_plural': 'Itens de NF',
                'ordering': ['nota_fiscal', 'tipo', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='SMVOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveSmallIntegerField(verbose_name='Versão')),
                ('fornecedor', models.CharField(max_length=120, verbose_name='Fornecedor / Oficina')),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=18, verbose_name='CNPJ Fornecedor')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor peças (R$)')),
                ('valor_mo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor mão de obra (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor total (R$)')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to=apps.manutencao.models._orcamento_upload, verbose_name='PDF do orçamento')),
                ('status', models.CharField(choices=[('EM_NEGOCIACAO', 'Em negociação'), ('AGUARD_APROVA', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='EM_NEGOCIACAO', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('smv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='manutencao.smv')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['smv', 'versao'],
                'unique_together': {('smv', 'versao')},
            },
        ),
        migrations.CreateModel(
            name='SMVAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_doc_fisico', models.CharField(choices=[('NAO_ENVIADO', 'Não enviado'), ('ENVIADO_RESP', 'Enviado ao Resp. Técnico'), ('ENVIADO_FISCAL', 'Enviado ao Fiscal da Pasta'), ('ENVIADO_SECRET', 'Enviado ao Secretário'), ('RETORNADO', 'Retornado à Gestão')], default='NAO_ENVIADO', max_length=20, verbose_name='Status doc. físico')),
                ('dt_envio_resp', models.DateField(blank=True, null=True, verbose_name='Envio ao Resp. Técnico')),
                ('dt_assin_resp', models.DateField(blank=True, null=True, verbose_name='Assinatura Resp. Técnico')),
                ('dt_envio_fiscal_pasta', models.DateField(blank=True, null=True, verbose_name='Envio ao Fiscal da Pasta')),
                ('dt_assin_fiscal_pasta', models.DateField(blank=True, null=True, verbose_name='Assinatura Fiscal da Pasta')),
                ('dt_envio_secretario', models.DateField(blank=True, null=True, verbose_name='Envio ao Secretário')),
                ('dt_assin_secretario', models.DateField(blank=True, null=True, verbose_name='Assinatura Secretário')),
                ('dt_aprovacao_final', models.DateTimeField(blank=True, null=True, verbose_name='Data de aprovação final')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('fiscal_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_fiscal_contrato', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal do contrato')),
                ('fiscal_pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_fiscal_pasta', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal da pasta')),
                ('resp_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_resp', to=settings.AUTH_USER_MODEL, verbose_name='Responsável técnico')),
                ('secretario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_secretario', to=settings.AUTH_USER_MODEL, verbose_name='Secretário')),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacao', to='manutencao.smvorcamento')),
            ],
            options={
                'verbose_name': 'Aprovação de orçamento',
                'verbose_name_plural': 'Aprovações de orçamento',
            },
        ),
    ]
