# Generated by Django 6.0.5 on 2026-06-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smv',
            name='num_processo',
        ),
        migrations.AlterField(
            model_name='smv',
            name='urgencia',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Urgência'),
        ),
    ]
