# Generated by Django 6.0.5 on 2026-06-14 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_remove_smv_num_processo_alter_smv_urgencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smvchecklist',
            name='ok',
        ),
        migrations.AddField(
            model_name='smvchecklist',
            name='condicao',
            field=models.CharField(choices=[('OK', 'OK'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('NA', 'N/A')], default='OK', max_length=8, verbose_name='Condição'),
        ),
        migrations.CreateModel(
            name='SMVRecepcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_entrada', models.PositiveIntegerField(verbose_name='KM de entrada')),
                ('nivel_combustivel', models.CharField(choices=[('RESERVA', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('CHEIO', 'Cheio')], max_length=10, verbose_name='Nível do combustível')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora de entrada')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Recepcionado por')),
                ('smv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcao', to='manutencao.smv')),
            ],
            options={
                'verbose_name': 'Recepção',
                'verbose_name_plural': 'Recepções',
            },
        ),
    ]
