# Generated by Django 6.0.5 on 2026-06-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_remove_smvchecklist_ok_smvchecklist_condicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smv',
            name='tipos_servico',
            field=models.CharField(blank=True, help_text='Lista separada por vírgula: MECANICA, ELETRICA, FUNILARIA, etc.', max_length=300, verbose_name='Tipos de serviço identificados'),
        ),
    ]
