# Generated by Django 6.0.5 on 2026-06-15 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_smv_tipos_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMVDiagnosticoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PECA', 'Peça'), ('SERVICO', 'Serviço / Mão de obra')], default='PECA', max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantidade')),
                ('unidade', models.CharField(default='pç', help_text='pç, m, l, h, kg, un, serv…', max_length=20, verbose_name='Unidade')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('smv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_diagnostico', to='manutencao.smv')),
            ],
            options={
                'verbose_name': 'Item do diagnóstico',
                'verbose_name_plural': 'Itens do diagnóstico',
                'ordering': ['tipo', 'descricao'],
            },
        ),
    ]
