# Generated by Django 6.0.5 on 2026-06-14 22:20

import apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMVMensagemLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida_em', models.DateTimeField(auto_now_add=True, verbose_name='Lida em')),
            ],
            options={
                'verbose_name': 'Leitura de mensagem',
                'verbose_name_plural': 'Leituras de mensagem',
            },
        ),
        migrations.CreateModel(
            name='SMVMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(help_text='Etapa da SMV no momento do envio — registrado automaticamente.', max_length=15, verbose_name='Etapa ao enviar')),
                ('texto', models.TextField(blank=True, verbose_name='Mensagem')),
                ('anexo', models.FileField(blank=True, null=True, upload_to=apps.chat.models._mensagem_anexo_upload, verbose_name='Anexo')),
                ('enviada_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_smv', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Mensagem SMV',
                'verbose_name_plural': 'Mensagens SMV',
                'ordering': ['enviada_em'],
            },
        ),
    ]
