# Generated by Django 6.0.5 on 2026-06-14 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('manutencao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smvmensagem',
            name='smv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='manutencao.smv', verbose_name='SMV'),
        ),
        migrations.AddField(
            model_name='smvmensagemleitura',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='chat.smvmensagem'),
        ),
        migrations.AddField(
            model_name='smvmensagemleitura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_smv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='smvmensagemleitura',
            unique_together={('mensagem', 'usuario')},
        ),
    ]
